In [1]:
import numpy as np

1. С помощью массивов numpy создайте таблицу умножения.

In [ ]:
table = np.zeros((9,9), int)
for i in range(1,11):
    table[i-2] = [x*(i-1) for x in range(1,10)]
table

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

2. Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число), и разность (вещественное число) и создает матрицу numpy по диагонали, которой располагаются первые N членов арифметической прогрессии.

In [ ]:
def f(n: int, first_number: float, different: float):
    diag = [first_number- (i*different) for i in range(n)]
    A = np.diag(diag)
    return A
f(10, 5, 0.5)

array([[5. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 4.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 4. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 3.5, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 3. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 2.5, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 2. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 1.5, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5]])

3. Сгенерируйте средствами numpy матрицу А 5 на 5, содержащую последовательные числа от 1 до 25. Используя срезы извлеките в плоский массив все нечетные элементы этой матрицы.

In [73]:
A = np.array(np.arange(1, 26)).reshape(5,5)
A1 = A[0:5:2, [0,2, 4]]
A2 = A[1:5:2, [1,3]]
A1 = A1.flatten()
A2 = A2.flatten()
Af = np.array([*A1, *A2])
Af

array([ 1,  3,  5, 11, 13, 15, 21, 23, 25,  7,  9, 17, 19])

4. Создайте двумерный массив, содержащий единицы на границе и нули внутри.

In [90]:
N = 5 
A = np.ones((N,N))
A[1:4, 1:4] = 0
A

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

5. Создайте две матрицы размером (5,5). Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания, другая имеет треугольную форму содержащую 5 на основной диагонали и в позициях выше ее, а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы.

In [ ]:
A = np.zeros([5,5])
A[0:5:2, 0:5:2] = 5
A[2:5:2, 2:5:2] = 5
A

In [113]:
B = np.zeros([5,5])
Z = np.triu_indices(B, k=0)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

AttributeError: 'numpy.ndarray' object has no attribute 'diag'