In [1]:
from sympy import *
import numpy as np
from scipy.linalg import *
init_printing()

![](pic/4/4.1.png)

In [18]:
A = np.array([
    [1, 2, 3],
    [0, -1, 1],
    [-2, 1, 0],
    [-1, 2, -3]
])


def P14(matrix):
    result = matrix.copy()
    result[[0, 3]] = result[[3, 0]]
    return result

A1 = P14(A)

def A42(k, matrix):
    result = matrix.copy()
    result[3] += k * result[1]
    return result

A2 = A42(1, A1)

def M3(k, matrix):
    result = matrix.copy()
    result[2] *= k
    return result

A3 = M3(-2, A2)

def A34(k, matrix):
    result = matrix.copy()
    result[2] += k * result[3] 
    return result

A4 = A34(-2, A3)

def P23(matrix):
    result = matrix.copy()
    result[[1, 2]] = result[[2, 1]]
    return result

B = P23(A4)
print(B)
print()

b32 = B[2, 1]
b23 = B[1, 2]

print(f"b32 = {b32}")
print(f"b23 = {b23}")

[[-1  2 -3]
 [ 2 -4 -8]
 [ 0 -1  1]
 [ 1  1  4]]

b32 = -1
b23 = -8


![](pic/4/4.2.png)

![](pic/4/4.3.png)

In [42]:
A = np.array([
    [1,3],
    [-5, 2]
])

np.linalg.inv(A)

array([[ 0.11764706, -0.17647059],
       [ 0.29411765,  0.05882353]])

In [45]:
A = np.array([
    [3,2],
    [1,3]
])
B = np.array([
    [2,5],
    [3, -2]
])
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
np.linalg.inv(A_inv*B_inv)

array([[ 12.09090909, -20.15151515],
       [ -6.04545455, -12.09090909]])

![](pic/4/4.4.png)

In [51]:
A = np.linalg.inv(np.array([[2,1], [3,1]]))
C = np.linalg.inv(np.array([[0,2], [1,4]]))
b = np.array([1,1]).reshape(2,1)
Ct = C.T
Ct * A / b 

array([[ 2. ,  0.5],
       [ 3. , -0. ]])

![](pic/4/4.5.png)

In [52]:
A = Matrix([
    [3, -1, 2],
    [5, -2, 3],
    [-1, 0, -1]
])

O3 = zeros(3)
A.pow(3) == O3

True

In [54]:
(A+ eye(3)).pow(-1)

⎡0   0  -1⎤
⎢         ⎥
⎢-3  2  -2⎥
⎢         ⎥
⎣-1  1  1 ⎦

![](pic/4/4.6.png)

In [61]:
I2 = eye(2) * 2
B = np.array([
    [2,1],
    [-1, 0]
])
B = np.linalg.inv(B)
B += 2*I2
B.T

⎡4.0   1.0⎤
⎢         ⎥
⎣-1.0  6.0⎦

![](pic/4/4.7.png)

In [64]:
A = Matrix([
    [1, -3, 6],
    [2, -5, 9],
    [3, -8, 16]
])
A.pow(-1)

⎡-8  0   3⎤
⎢         ⎥
⎢-5  -2  3⎥
⎢         ⎥
⎣-1  -1  1⎦

![](pic/4/4.8.png)

![](pic/4/4.9.png)

![](pic/4/4.10.png)

![](pic/4/4.11.png)

![](pic/4/4.12.png)

![](pic/4/4.13.png)