#1.6

In [5]:
import numpy as np
import scipy.linalg as la
from sympy import *
init_printing()

In [6]:
A = np.array([[1, 5, -2, 0], [-3, 1, 9, -5], [4, -8, -1, 7]])
A

array([[ 1,  5, -2,  0],
       [-3,  1,  9, -5],
       [ 4, -8, -1,  7]])

In [7]:
b = np.array([-7, 9, 0]).reshape(3,1)
b

array([[-7],
       [ 9],
       [ 0]])

In [9]:
A_b = np.hstack([A,b])
A_b

array([[ 1,  5, -2,  0, -7],
       [-3,  1,  9, -5,  9],
       [ 4, -8, -1,  7,  0]])

In [10]:
Matrix(A_b).rref()

⎛⎡1  0  0  8/7   -11/7⎤           ⎞
⎜⎢                    ⎥           ⎟
⎜⎢0  1  0  -2/7  -6/7 ⎥, (0, 1, 2)⎟
⎜⎢                    ⎥           ⎟
⎝⎣0  0  1  -1/7   4/7 ⎦           ⎠

#1.7

In [65]:
import numpy as np
import scipy.linalg as la
from sympy import *
init_printing()

In [ ]:
A = np.array([[5, -1, 5, 9, -2],
              [3, 0, 6, 9, -1],
              [2, 0, 4, 6, -1]])

In [82]:
b = np.array([[-3], [4], [0]]).reshape(3,1)

In [83]:
A_b = np.hstack([A,b])

In [84]:
Matrix(A_b).rref()

⎛⎡1  0  2  3  0  4⎤           ⎞
⎜⎢                ⎥           ⎟
⎜⎢0  1  5  6  0  7⎥, (0, 1, 4)⎟
⎜⎢                ⎥           ⎟
⎝⎣0  0  0  0  1  8⎦           ⎠

In [ ]:
x1,x2,x3,x4,x5 = symbols("x1 x2 x3 x4 x5")
#free - 3 4 

In [98]:
eq1 = Eq(x1 + 2*x3 + 3*x4, 4)
eq2 = Eq(x2 + 5*x3 + 6*x4, 7)
eq3 = Eq(x5, 8)

In [101]:
answer = solve([eq1,eq2,eq3], [x1,x2,x5])

In [103]:
print(answer[x1])
print(answer[x2])
print(answer[x5])

-2*x3 - 3*x4 + 4
-5*x3 - 6*x4 + 7
8


# БИЛЕТ 101

In [1]:
from sympy import *
init_printing()

In [ ]:
# x y z u 
A = Matrix([
    [16, 39, 38, 21, 28],
    [17, 70, 79, 48, 31],
    [27, 18, 21, 13, 45]
])
A.rref()

⎛⎡                  671  ⎤           ⎞
⎜⎢1  0  0  1/9840   ───  ⎥           ⎟
⎜⎢                  410  ⎥           ⎟
⎜⎢                       ⎥           ⎟
⎜⎢         -643     11   ⎥           ⎟
⎜⎢0  1  0  ─────    ───  ⎥, (0, 1, 2)⎟
⎜⎢         1640     205  ⎥           ⎟
⎜⎢                       ⎥           ⎟
⎜⎢          9397         ⎥           ⎟
⎜⎢0  0  1   ────   -3/410⎥           ⎟
⎝⎣          9840         ⎦           ⎠

In [ ]:
A.col_swap(0,3)
#u y z x
A.rref()

⎛⎡1  0  0  9840   16104 ⎤           ⎞
⎜⎢                      ⎥           ⎟
⎜⎢0  1  0  3858    6314 ⎥, (0, 1, 2)⎟
⎜⎢                      ⎥           ⎟
⎝⎣0  0  1  -9397  -15379⎦           ⎠

In [ ]:
#y = 6314 - 3858x
# answer 

In [21]:
#2
A = Matrix([
    [9, 8, 4],
    [5,5,6]
])
B = Matrix([
    [1, 7, 2],
    [7, 7, 2]
])
C = A.T * B
D = A * B.T 
K = kronecker_product(C, D)

In [23]:
C.trace()

In [24]:
K.trace()

In [25]:
#3 
A = Matrix([
    [6,7],
    [3,2]
])
B = Matrix([
    [8,9],
    [3,4]
])
C = Matrix([
    [31, 30],
    [12, 23]
])
# AXB = C
X = (A**-1) * C * (B**-1)


In [26]:
X.trace()

In [27]:
sum(X)

In [28]:
X

⎡-43/9  122/9⎤
⎢            ⎥
⎢ 76    -191 ⎥
⎢ ──    ─────⎥
⎣ 15     15  ⎦

In [ ]:
#4
for t in range(1000):
    A = Matrix([
        [8,8,2,1],
        [t,5,4,0],
        [0,1,6,4],
        [8,8,6,4]
    ])
    B = Matrix([
        [6,0,5,6],
        [5, 1, 0, 2],
        [1, 5, 0, 6],
        [6,9,3,6]
    ])
    C = A*B 
    C

⎡   96     27  43      82   ⎤
⎢                           ⎥
⎢6⋅t + 29  25  5⋅t  6⋅t + 34⎥
⎢                           ⎥
⎢   35     67  12      62   ⎥
⎢                           ⎥
⎣  118     74  52     124   ⎦