#1.6

In [1]:
import numpy as np
import scipy.linalg as la
from sympy import *
init_printing()

In [6]:
A = np.array([[1, 5, -2, 0], [-3, 1, 9, -5], [4, -8, -1, 7]])
A

array([[ 1,  5, -2,  0],
       [-3,  1,  9, -5],
       [ 4, -8, -1,  7]])

In [7]:
b = np.array([-7, 9, 0]).reshape(3,1)
b

array([[-7],
       [ 9],
       [ 0]])

In [9]:
A_b = np.hstack([A,b])
A_b

array([[ 1,  5, -2,  0, -7],
       [-3,  1,  9, -5,  9],
       [ 4, -8, -1,  7,  0]])

In [10]:
Matrix(A_b).rref()

⎛⎡1  0  0  8/7   -11/7⎤           ⎞
⎜⎢                    ⎥           ⎟
⎜⎢0  1  0  -2/7  -6/7 ⎥, (0, 1, 2)⎟
⎜⎢                    ⎥           ⎟
⎝⎣0  0  1  -1/7   4/7 ⎦           ⎠

#1.7

In [65]:
import numpy as np
import scipy.linalg as la
from sympy import *
init_printing()

In [ ]:
A = np.array([[5, -1, 5, 9, -2],
              [3, 0, 6, 9, -1],
              [2, 0, 4, 6, -1]])

In [82]:
b = np.array([[-3], [4], [0]]).reshape(3,1)

In [83]:
A_b = np.hstack([A,b])

In [84]:
Matrix(A_b).rref()

⎛⎡1  0  2  3  0  4⎤           ⎞
⎜⎢                ⎥           ⎟
⎜⎢0  1  5  6  0  7⎥, (0, 1, 4)⎟
⎜⎢                ⎥           ⎟
⎝⎣0  0  0  0  1  8⎦           ⎠

In [ ]:
x1,x2,x3,x4,x5 = symbols("x1 x2 x3 x4 x5")
#free - 3 4 

In [98]:
eq1 = Eq(x1 + 2*x3 + 3*x4, 4)
eq2 = Eq(x2 + 5*x3 + 6*x4, 7)
eq3 = Eq(x5, 8)

In [101]:
answer = solve([eq1,eq2,eq3], [x1,x2,x5])

In [103]:
print(answer[x1])
print(answer[x2])
print(answer[x5])

-2*x3 - 3*x4 + 4
-5*x3 - 6*x4 + 7
8


# БИЛЕТ 101

In [1]:
from sympy import *
init_printing()

In [ ]:
# x y z u 
A = Matrix([
    [16, 39, 38, 21, 28],
    [17, 70, 79, 48, 31],
    [27, 18, 21, 13, 45]
])
A.rref()

⎛⎡                  671  ⎤           ⎞
⎜⎢1  0  0  1/9840   ───  ⎥           ⎟
⎜⎢                  410  ⎥           ⎟
⎜⎢                       ⎥           ⎟
⎜⎢         -643     11   ⎥           ⎟
⎜⎢0  1  0  ─────    ───  ⎥, (0, 1, 2)⎟
⎜⎢         1640     205  ⎥           ⎟
⎜⎢                       ⎥           ⎟
⎜⎢          9397         ⎥           ⎟
⎜⎢0  0  1   ────   -3/410⎥           ⎟
⎝⎣          9840         ⎦           ⎠

In [ ]:
A.col_swap(0,3)
#u y z x
A.rref()

⎛⎡1  0  0  9840   16104 ⎤           ⎞
⎜⎢                      ⎥           ⎟
⎜⎢0  1  0  3858    6314 ⎥, (0, 1, 2)⎟
⎜⎢                      ⎥           ⎟
⎝⎣0  0  1  -9397  -15379⎦           ⎠

In [ ]:
#y = 6314 - 3858x
# answer 

In [21]:
#2
A = Matrix([
    [9, 8, 4],
    [5,5,6]
])
B = Matrix([
    [1, 7, 2],
    [7, 7, 2]
])
C = A.T * B
D = A * B.T 
K = kronecker_product(C, D)

In [23]:
C.trace()

In [24]:
K.trace()

In [69]:
#3 
A = Matrix([
    [6,7],
    [3,2]
])
B = Matrix([
    [8,9],
    [3,4]
])
C = Matrix([
    [31, 30],
    [12, 23]
])
# AXB = C
X = A.inv() * C * B.inv()


In [70]:
X.trace()


In [71]:
sum(X)


In [28]:
X

⎡-43/9  122/9⎤
⎢            ⎥
⎢ 76    -191 ⎥
⎢ ──    ─────⎥
⎣ 15     15  ⎦

In [73]:
t = symbols("t")
A = Matrix([
    [8,8,2,1],
    [t,5,4,0],
    [0,1,6,4],
    [8,8,6,4]
])
B = Matrix([
    [6, 0, 5, 6],
    [5, 1, 0, 2],
    [ 1, 5, 0,  6],
    [6 , 9, 3, 6]
])
C = A*B
d = C.det()
factor(d)

In [58]:
p = [12, 10, 9, 4, 7, 6, 8, 2, 11, 3, 1, 5]
perm = [i-1 for i in p]
mat = []
for j in range(12):
    i = perm[j]
    line = [0 for i in range(12)]
    line[i] = 1
    mat.append(line)
A = Matrix(mat)

In [59]:
(A**4).trace()

In [60]:
for i in range(1, 100000):
    if (A**i).trace() == 12:
        print(i)
        break

10


# 4 билет 

In [2]:
#3 
gamma = 0.072
I = eye(2)
A = Matrix([
    [6*gamma, 3 *gamma],
    [7*gamma, 9*gamma]
])


In [3]:
S = zeros(2,2)
for i in range(4, 101):
    S += A ** i 
max(S)


In [4]:
B4 = (I-A).inv() * A**4
max(B4)

In [5]:
for k in range(1000):
    n = 0 
    while True:
        n+=1
        temp = zeros(2,2)
        for i in range(k,n+1):
            temp += A**i 
        if max(temp) >= 0.002:
            break
        print(n, k)

1 2
1 3
2 3
1 4
2 4
3 4
1 5
2 5
3 5
4 5
1 6
2 6
3 6
4 6
5 6
1 7
2 7
3 7
4 7
5 7
6 7
1 8
2 8
3 8
4 8
5 8
6 8
7 8
1 9
2 9
3 9
4 9
5 9
6 9
7 9
8 9
1 10
2 10
3 10
4 10
5 10
6 10
7 10
8 10
9 10
1 11
2 11
3 11
4 11
5 11
6 11
7 11
8 11
9 11
10 11
1 12
2 12
3 12
4 12
5 12
6 12
7 12
8 12
9 12
10 12
11 12
1 13
2 13
3 13
4 13
5 13
6 13
7 13
8 13
9 13
10 13
11 13
12 13
1 14
2 14
3 14
4 14
5 14
6 14
7 14
8 14
9 14
10 14
11 14
12 14
13 14
1 15
2 15
3 15
4 15
5 15
6 15
7 15
8 15
9 15
10 15
11 15
12 15
13 15
14 15
1 16
2 16
3 16
4 16
5 16
6 16
7 16
8 16
9 16
10 16
11 16
12 16
13 16
14 16
15 16
1 17
2 17
3 17
4 17
5 17
6 17
7 17
8 17
9 17
10 17
11 17
12 17
13 17
14 17
15 17
16 17
1 18
2 18
3 18
4 18
5 18
6 18
7 18
8 18
9 18
10 18
11 18
12 18
13 18
14 18
15 18
16 18
17 18
1 19
2 19
3 19
4 19
5 19
6 19
7 19
8 19
9 19
10 19
11 19
12 19
13 19
14 19
15 19
16 19
17 19
18 19
1 20
2 20
3 20
4 20
5 20
6 20
7 20
8 20
9 20
10 20
11 20
12 20
13 20
14 20
15 20
16 20
17 20
18 20
19 20
1 21
2 21
3 21
4 21
5 21
6 21
7

KeyboardInterrupt: 

In [6]:
x = symbols("x")
M = Matrix([
    [4, 0, 6, 0],
    [x, 2, 6, 4],
    [6 ,7,8,x],
    [4,4,7,0]
])
M.det()