#1.6

In [5]:
import numpy as np
import scipy.linalg as la
from sympy import *
init_printing()

In [6]:
A = np.array([[1, 5, -2, 0], [-3, 1, 9, -5], [4, -8, -1, 7]])
A

array([[ 1,  5, -2,  0],
       [-3,  1,  9, -5],
       [ 4, -8, -1,  7]])

In [7]:
b = np.array([-7, 9, 0]).reshape(3,1)
b

array([[-7],
       [ 9],
       [ 0]])

In [9]:
A_b = np.hstack([A,b])
A_b

array([[ 1,  5, -2,  0, -7],
       [-3,  1,  9, -5,  9],
       [ 4, -8, -1,  7,  0]])

In [10]:
Matrix(A_b).rref()

⎛⎡1  0  0  8/7   -11/7⎤           ⎞
⎜⎢                    ⎥           ⎟
⎜⎢0  1  0  -2/7  -6/7 ⎥, (0, 1, 2)⎟
⎜⎢                    ⎥           ⎟
⎝⎣0  0  1  -1/7   4/7 ⎦           ⎠

#1.7

In [65]:
import numpy as np
import scipy.linalg as la
from sympy import *
init_printing()

In [ ]:
A = np.array([[5, -1, 5, 9, -2],
              [3, 0, 6, 9, -1],
              [2, 0, 4, 6, -1]])

In [82]:
b = np.array([[-3], [4], [0]]).reshape(3,1)

In [83]:
A_b = np.hstack([A,b])

In [84]:
Matrix(A_b).rref()

⎛⎡1  0  2  3  0  4⎤           ⎞
⎜⎢                ⎥           ⎟
⎜⎢0  1  5  6  0  7⎥, (0, 1, 4)⎟
⎜⎢                ⎥           ⎟
⎝⎣0  0  0  0  1  8⎦           ⎠

In [ ]:
x1,x2,x3,x4,x5 = symbols("x1 x2 x3 x4 x5")
#free - 3 4 

In [98]:
eq1 = Eq(x1 + 2*x3 + 3*x4, 4)
eq2 = Eq(x2 + 5*x3 + 6*x4, 7)
eq3 = Eq(x5, 8)

In [101]:
answer = solve([eq1,eq2,eq3], [x1,x2,x5])

In [103]:
print(answer[x1])
print(answer[x2])
print(answer[x5])

-2*x3 - 3*x4 + 4
-5*x3 - 6*x4 + 7
8
