# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [3]:
import numpy as np

## Разминка

1. Сгенерировать двухмерный массив arr размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0
2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.
3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности
4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [5]:
#1
dataset = np.loadtxt(r"C:\Users\Сергей\YandexDisk\Python\Ipynb\TOBD_2021\TOBD21_for_students\01_numpy\sem\data\minutes_n_ingredients.csv", 
                     delimiter=',', skiprows=1, dtype=np.int32)
dataset[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [31]:
print(dataset[:, 1:].mean(axis=0),
      dataset[:, 1:].min(axis=0),
      dataset[:, 1:].max(axis=0),
      np.median(dataset[:, 1:], axis=0), sep='\n')

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [50]:
q = np.quantile(dataset[:, 1], q=0.75)
dataset[:, 1] = dataset[:, 1].clip(max=q)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [1]:
print(dataset[dataset[:, 1]==0].shape)
dataset[dataset[:, 1]==0, 1] = 1

NameError: name 'dataset' is not defined

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [52]:
len(np.unique(dataset[:, 0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [71]:
np.unique(dataset[:, 2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39])

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [55]:
dataset[dataset[:, 2]<=5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [61]:
dataset[:, 2] / dataset[:, 1]

array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.21538462])

In [63]:
(dataset[:, 2] / dataset[:, 1]).max()

23.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [65]:
rows = dataset[:, 1].argsort()[-100:]
dataset[rows, 2].mean()

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [66]:
dataset[np.random.randint(0, len(dataset), 10)]

array([[241212,     50,      7],
       [223183,     10,      5],
       [115863,     65,     11],
       [165845,     50,     13],
       [378101,     30,     10],
       [136739,      1,      2],
       [241644,     65,     10],
       [ 77017,     40,      5],
       [435267,     65,      7],
       [233865,     40,      6]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [67]:
len(dataset[dataset[:, 2]<dataset[:, 2].mean()]) / len(dataset)

0.58989

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [69]:
dataset_big = np.zeros((len(dataset), 4), dtype=np.int32)
dataset_big[:, :3] = dataset
dataset_big[:, 3] = (dataset[:, 1] <= 20) & (dataset[:, 2] <= 5).astype(np.int32)

13. Выведите процент "простых" рецептов в датасете

In [70]:
easy = (dataset_big[:, -1] == 1).sum()
easy/len(dataset_big), 1 - easy/len(dataset_big)

(0.09943, 0.90057)

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [78]:
short = dataset[dataset[:, 2] < 10]
standart = dataset[(dataset[:, 2] >= 10) & (dataset[:, 2] < 20)]
long = dataset[dataset[:, 2] >= 20]

max_n = min(len(short), len(standart), len(long))
arr = np.stack([short[:max_n], standart[:max_n], long[:max_n]])

In [79]:
arr.shape

(3, 1070, 3)